language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: 7.4

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer cs-check

